### ISSUE TITLE
Implement proper data classes

### ISSUE THREAD

**Issue by lamr02n** [stefanDeveloper/heiDGAF#43]
## Summary
We should add two classes `Logline` and `Batch`. A `Logline` contains the fields of the log entry. A `Batch` contains a field `data`, which is a list of `Logline` objects, and possibly more fields such as timestamps, which we could store as `metadata`.

### Basic example
We could use this structure:
```
from dataclasses import dataclass
from typing import List
from datetime import datetime

@dataclass
class Logline:
    fields: List[str]

@dataclass
class Batch:
    loglines: List[Logline]
    begin_timestamp: datetime
    end_timestamp: datetime
```

Additionally, to allow sending via Kafka, we must serialize the objects with schemas:
```
from marshmallow import Schema, fields, post_load

class LoglineSchema(Schema):
    data = fields.Str()

    @post_load
    def make_logline(self, data, **kwargs):
        return Logline(**data)

class BatchSchema(Schema):
    loglines = fields.List(fields.Nested(LoglineSchema))
    begin_timestamp = fields.DateTime()
    end_timestamp = fields.DateTime()

    @post_load
    def make_batch(self, data, **kwargs):
        return Batch(**data)
```

Accordingly, the Kafka Handling classes and the data types in the modules must be changed.

### Motivation
As of right now, we have the problem that there are multiple different states, in which data can be: strings of single log lines, strings of JSON like objects via `json.dumps()`, dictionaries and more. This can lead to confusion regarding the used types in a module and requires "translating" data types quite frequently. The `Inspector` and `Detector` currently use something called a `Batch`. We should make this mandatory for all data used.

**Comment by stefanDeveloper** [comment]
This enhancement should be done with #57, please confirm, so we can close it.

**Comment by lamr02n** [comment]
> This enhancement should be done with #57, please confirm, so we can close it.

Yes, this has been handled by #57
